In [1]:
##================================================
## このセルを最初に実行せよ---Run this cell first.
##================================================
!wget -P . https://raw.githubusercontent.com/utokyo-ipp/utokyo-ipp.github.io/master/colab/5/factorial.py
!wget -P fig https://raw.githubusercontent.com/utokyo-ipp/utokyo-ipp.github.io/master/colab/5/fig/py_conv_1.png
!wget -P fig https://raw.githubusercontent.com/utokyo-ipp/utokyo-ipp.github.io/master/colab/5/fig/py_conv_2.png
!wget -P fig https://raw.githubusercontent.com/utokyo-ipp/utokyo-ipp.github.io/master/colab/5/fig/py_open_1.png
!wget -P fig https://raw.githubusercontent.com/utokyo-ipp/utokyo-ipp.github.io/master/colab/5/fig/py_open_2.png

--2023-04-15 12:24:49--  https://raw.githubusercontent.com/utokyo-ipp/utokyo-ipp.github.io/master/colab/5/factorial.py
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.109.133, 185.199.110.133, 185.199.111.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.109.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 109 [text/plain]
Saving to: './factorial.py'

factorial.py        100%[===================>]     109  --.-KB/s    in 0s      

2023-04-15 12:24:50 (10.4 MB/s) - './factorial.py' saved [109/109]

--2023-04-15 12:24:50--  https://raw.githubusercontent.com/utokyo-ipp/utokyo-ipp.github.io/master/colab/5/fig/py_conv_1.png
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.109.133, 185.199.110.133, 185.199.111.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.109.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 27

In [2]:
import numpy as np

In [3]:
a = np.array([1,2,3])
print(a)

b = np.array((1,2,3))
print(b)

[1 2 3]
[1 2 3]


In [4]:
type(np.array([1,2,3,4,5]))

numpy.ndarray

In [5]:
type([1,2,3,4,5])

list

In [6]:
print(np.array([-1,0,1], dtype=np.int32))

[-1  0  1]


In [7]:
print(np.array([-1, 0, 1], dtype=np.float64))

[-1.  0.  1.]


In [8]:
print(np.array([-1, 0, 1], dtype=np.complex128))

[-1.+0.j  0.+0.j  1.+0.j]


In [9]:
print(np.array([-1,0,1], dtype=np.bool_))

[ True False  True]


In [10]:
print(np.array([[1,2],[3,4]]))

[[1 2]
 [3 4]]


In [11]:
print(np.array([[[1,2],[3,4]],[[5,6],[7,8]]]))

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [12]:
print(np.array([[1,2],[3]]))

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.

In [13]:
a1 = np.array([0, 1, 2, 3, 4, 5])
a2 = a1.reshape(2, 3)
a2

array([[0, 1, 2],
       [3, 4, 5]])

In [14]:
a1[1] = 6
print(a1)
print(a2)

[0 6 2 3 4 5]
[[0 6 2]
 [3 4 5]]


In [17]:
a = np.array([0, 1, 2, 3, 4, 5]).reshape(2,3)
print(a)
print(a.ravel())

[[0 1 2]
 [3 4 5]]
[0 1 2 3 4 5]


In [18]:
elems = np.array([0,1,2,3,4,5])
a = elems.reshape(2,3).ravel()
elems[1] = 6
print(a)

[0 6 2 3 4 5]


In [19]:
print(np.arange(3))
print(np.arange(0, 1, 0.2))

[0 1 2]
[0.  0.2 0.4 0.6 0.8]


In [20]:
print(np.linspace(0, 1, 4))

[0.         0.33333333 0.66666667 1.        ]


In [22]:
print(np.zeros(4))
print(np.zeros((2,3)))
print(np.ones(4))
print(np.ones((2,3)))

[0. 0. 0. 0.]
[[0. 0. 0.]
 [0. 0. 0.]]
[1. 1. 1. 1.]
[[1. 1. 1.]
 [1. 1. 1.]]


In [24]:
print(np.random.rand(4))
print(np.random.rand(2, 3))

[0.70538496 0.52416048 0.34585797 0.89396857]
[[0.52449816 0.36274995 0.91799329]
 [0.93579596 0.56261722 0.91144453]]


In [31]:
def arange_square_matrix(n):
    return np.array([np.arange(i, n+i) for i in range(n)])


In [32]:
print(all(map(all,(arange_square_matrix(3) == np.array([[0,1,2],[1,2,3],[2,3,4]])))))

True


In [33]:
a = np.arange(3)
print(a)

[0 1 2]


In [34]:
a[0]

0

In [35]:
a[-1]

2

In [36]:
a[-1] = 3
print(a)

[0 1 3]


In [37]:
a = np.arange(6).reshape(2,3)
print(a)

[[0 1 2]
 [3 4 5]]


In [38]:
a[1,2]

5

In [39]:
a[1,2] = 6
print(a)

[[0 1 2]
 [3 4 6]]


In [40]:
a = np.arange(5)
print(a)
print(a[1:4])
print(a[1:])
print(a[:-2])
print(a[::2])
print(a[::-1])

[0 1 2 3 4]
[1 2 3]
[1 2 3 4]
[0 1 2]
[0 2 4]
[4 3 2 1 0]


In [41]:
a = np.arange(5)
print(a)
a[1:4] = 6
print(a)
a = np.arange(5)
a[::2] = 6
print(a)

[0 1 2 3 4]
[0 6 6 6 4]
[6 1 6 3 6]


In [42]:
a = [0,1,2,3,4]
print(a)
a[1:4] = 6

[0, 1, 2, 3, 4]


TypeError: can only assign an iterable

In [43]:
a = [0,1,2,3,4]
print(a)
a[1:4] = [6]
print(a)

[0, 1, 2, 3, 4]
[0, 6, 4]


In [44]:
a = np.arange(9).reshape(3,3)
print(a)
print(a[:2,:2])
print(a[1:,1:])

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[0 1]
 [3 4]]
[[4 5]
 [7 8]]


In [45]:
for vars in np.arange(3):
    print(v)

NameError: name 'v' is not defined